backend:
  name: github
  repo: davidborelli/dborelli-blog
  branch: master
  site_domain: https://www.dborelli.com.br/

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "/assets/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "image", name: "thumbnail", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["JS", "HTML", "tips", "dev"],
        }
      - {
          label: "Background",
          name: "background",
          widget: "select",
          options:
            [
              { label: "JS", value: "#D6BA32" },
              { label: "HTML", value: "#e34d26" },
              { label: "tips", value: "#63935D" },
              { label: "dev", value: "#D50287" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
